name: Create Release
on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest tag details
        id: get_tag_details
        run: |
          echo ::set-output name=tag_name::$(git describe --tags --abbrev=0 HEAD)
          echo ::set-output name=tag_message::$(git tag -n --format='%(contents)' $(git describe --tags --abbrev=0 HEAD))
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag_details.outputs.tag_name }}
          release_name: ${{ steps.get_tag_details.outputs.tag_name }}
          body: ${{ steps.get_tag_details.outputs.tag_message }}
